# Generated by Django 2.1 on 2019-06-25 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cf_is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='cf_stream_uui',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
