# Generated by Django 2.1 on 2019-12-06 15:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import wagtailmedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_auto_20190625_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cf_json_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=wagtailmedia.models.json_response_default_value, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='cf_stream_uui',
            field=models.CharField(default='', max_length=256),
        ),
    ]